import 'package:flutter/material.dart';

/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
///

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData moon_inv =
      const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData fontsize =
      const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData paper_plane =
      const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData paper_plane_2 =
      const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData paper_plane_1 =
      const IconData(0xf1d8, fontFamily: _kFontFam);
}
